### ISSUE TITLE
Design by contract: text does not follow it's own advice

### ISSUE THREAD

**Issue by mircokroon** [sttp-book/sttp-book#101]
Early on in the Design by contract chapter, a hint states:
```
Always include a message that describes what is going wrong if the assertion is failing.
```

However, not a single code example after that point actually provides such a message. I think it might not really encourage students to use these messages if even the book cannot be bothered to actually include them anywhere. Perhaps it would be a good idea to add these messages to all of the examples?

**Comment by mauricioaniche** [comment]
Yes, let us add the messages there. Can you do that, @mircokroon?

(We should also propagate the changes to the code-examples repo)

**Comment by mircokroon** [comment]
I've added them to the chapter in the book in PR #102 . I left them out in the exercises as figuring out exactly what the asserts are doing could be considered part of the exercise.
