### ISSUE TITLE
Consistent hyphenation ("pre-condition" or "precondition"?)

### ISSUE THREAD

**Issue by mircokroon** [sttp-book/sttp-book#103]
In the Design by contract chapter, there was usage of both "pre-condition" and "precondition". In this chapter I replaced all of the non-hyphenated ones with hyphens.

I noticed that in the rest of the book there are more of these cases where this is not written consistently, perhaps these should all be made into the hyphen-including variants, as this seems to be used more commonly in the book.

In one of the videos linked in the book a similar issue is present, as the title of the video uses a different convention than the very first frame of the same video. ("Pre and Post-conditions" or "Pre- and Postconditions"). Currently the book uses "Pre- and Post-conditions" which I believe is the correct usage when joining two hyphenated words [according to wikipedia](https://en.wikipedia.org/wiki/Hyphen#Suspended_hyphens).

![image](https://user-images.githubusercontent.com/23699979/79896048-209d3580-8408-11ea-9b58-a218fdb00d6b.png)

**Comment by mauricioaniche** [comment]
Thanks for catching it! I see you already fixed it in PR #102 (so, we can close this one, once the PR is merged). In the videos, that will be tough to do, though.

**Comment by mircokroon** [comment]
Actually this issue was meant for all the other instances where this is used, I did a quick search through the book and found there were places in other chapters as well with this issue. I didn't want to change those as they may cause conflicts with some of the other reviews.

**Comment by mauricioaniche** [comment]
PR #102 was merged, so I'm closing this issue!
