### ISSUE TITLE
Category-partition: code block spoils student exercise introduced in video

### ISSUE THREAD

**Issue by HellboundHound** [sttp-book/sttp-book#105]
The second video regarding the **Category-Partition Method** ends with Mauricio saying that the last two tests have to be implemented as an exercise by the student. However, these two tests are already covered in the code block above the video. Therefore, spoiling the result before the video.

**Comment by mauricioaniche** [comment]
That's true, @HellboundHound! In the videos (that were mainly done for edX), I had to be short and concise. In the book, we have more space. 

I'll leave this issue open and see if our media center can simply remove that last sentence from the video!

**Comment by mauricioaniche** [comment]
Given that the set of videos should also work without the text (for our previous edX edition), we can't really edit it. 

So, it will be a bit of a bummer for students that are reading and watching, but nothing that harms learning, hopefully!
