### ISSUE TITLE
Error in Exercise

### ISSUE THREAD

**Issue by jaroniboy** [sttp-book/sttp-book#110]
In exercise 2 of the paragraph specification-based testing is a mistake.
In the explanation it states "divisible by 5 use Buzz", but in the example it states "5 yields Fizz"
The example should be changed to "5 yields Buzz"

**Comment by HellboundHound** [comment]
Solved: https://github.com/sttp-book/sttp-book/pull/107/commits/9371b95dd76fc27f0f0e57d800d0a591ca0bf6f3

**Comment by mauricioaniche** [comment]
Thanks for catching it!
