### ISSUE TITLE
Exercise 2 Boundary Testing

### ISSUE THREAD

**Issue by willemstuijt** [sttp-book/sttp-book#113]
I don't find this exercise really appropriate. For the % operator there can be multiple On points. So for n % 3 == 0 the on points are actually all multiples of 3 and not just 3.

**Comment by mauricioaniche** [comment]
Hi, @willemstuijt! That's a great observation!!

The `f(n) = n % 3` function is not a linear function.

<img width="1440" alt="mod" src="https://user-images.githubusercontent.com/100812/80183342-f23a7880-8608-11ea-84bf-feac80cf5f4d.png">
(made with desmos.com)

Therefore, there's no single _on_ and _off_ point, as you observed, but many. Looking at the picture, we can see that.

Pragmatically speaking, a tester would then pick one random _on point_ and its respective _off_ point. Moreover, as we'll see later, we can combine the information of the requirements themselves plus the source code, to get more confident. If a developer implemented this boundary by means of a `if(n % 3 == 0) { ... } else { ... }`, exercising the two branches (and the boundary) might be sufficient.

Does that answer your question?

Suggestion to improve the book:
1. Add an exercise that asks students to think of on and off points of equalities, e.g., `x == 10` or `x+1 ==15`.
2. Move this current exercise more to the end, and in the answer, explain that the function is non-linear, and thus, there's not a single on and off point.

Are you up for it?

**Comment by willemstuijt** [comment]
I hope I did it right. First pull request I've ever done.

**Comment by mauricioaniche** [comment]
It was perfect! Thanks for closing the issue too!
