### ISSUE TITLE
Specification-based testing Exercise 7- Enhance answer

### ISSUE THREAD

**Issue by MatthijsdeGoede** [sttp-book/sttp-book#117]
![image](https://user-images.githubusercontent.com/55321868/80283108-ab867480-8715-11ea-8f5d-5a3266554c0c.png)

![image](https://user-images.githubusercontent.com/55321868/80283099-9e698580-8715-11ea-904e-ceb3a79e4b47.png)

For point 1, I would suggest to treat no-filename with this name and omitted as exceptional for Filename, in addition to the current exceptional cases.

For point 2, I would suggest perform all other checks only when the given filename is actually valid, as it wouldn't make sense to look for occurances in case the file cannot be opened.

**Comment by MatthijsdeGoede** [comment]
Can I just change the answer and propose a MR or is this up to you?

**Comment by mauricioaniche** [comment]
You can open a PR!!!

For your point 1, adding another “action” there seems good!

Your point 2 does not seem necessary, as the only partition we are leaving
unrestricted for “file name” is “valid file name”, which means this one
will be combined with all the others! (That’s the all idea of the category
partition method. Once you analyzed all categories and their partitions,
you combine them all; if the number of combinations is too many, you then
try to reduce it by adding some constraints).

Thanks!
-- 
--
Maurício Aniche
Delft University of Technology
http://www.mauricioaniche.com

**Comment by mauricioaniche** [comment]
Hi, @MatthijsdeGoede! Did you do it? I can't remember anymore :)

**Comment by MatthijsdeGoede** [comment]
Yes I did this and I also filled the form if correct.

Kind regards,
Matthijs de Goede

Op zo 3 mei 2020 om 10:11 schreef Maurício Aniche <notifications@github.com

**Comment by MatthijsdeGoede** [comment]
Done!
