### ISSUE TITLE
Improve TDD chapter

### ISSUE THREAD

**Issue by fm2003** [sttp-book/sttp-book#130]
* [x] Copy the useful parts from the "TDD from the trenches" section to the first part of the chapter. For instance, it is interesting to know that you have done a study where developers wrote code with and without using TDD (maybe add a reference to the study, if you have one?). And some of the insights they mentioned may have not yet been incorporated in the rest of the chapter.
* [x] After that, delete the "TDD from the trenches" section. It is quite repetitive and has been written quite informally. Much of the information is already contained in the first part of the chapter. 
* [x] Eliminate any repetition that may be left in the chapter. For example, the phrase "first write the tests and then the production code" is repeated over and over.

**Comment by mauricioaniche** [comment]
Just did the first two. Maybe you want to review it again, @fm2003 ?

**Comment by mauricioaniche** [comment]
Just reviewed again, and it looks good. Closing it.
