### ISSUE TITLE
Typo in boundary testing chapter

### ISSUE THREAD

**Issue by bjornsweeper** [sttp-book/sttp-book#160]
"Let us **know** explore the boundaries between other partitions. The figure below shows which boundaries can happen (and that we should test):"

**Comment by mauricioaniche** [comment]
Hi, @bjornsweeper! Would you mind opening a PR that fixes the typo (and getting some bonus points, if you are CSE1110 student?)

**Comment by mauricioaniche** [comment]
This was fixed in some PR already!
