### ISSUE TITLE
Design for testability Exercise 3 has an incorrect answer

### ISSUE THREAD

**Issue by willemstuijt** [sttp-book/sttp-book#170]
The question asks you for the 2 most important improvements and the answer has 3 most important improvements. Besides, answer 1 is not included in the correct answers but it is described as correct in the explanation of the answer. While answer 2 is included in the correct answers but in the explanation of the answer it is said to be wrong. I thought the answer was 1 and 3. I'm confused.

**Comment by mauricioaniche** [comment]
I tried to clarify it: https://github.com/sttp-book/sttp-book/commit/863689da65b26699bf9539bd39b4a17e1b95303e

Is it better?

**Comment by willemstuijt** [comment]
Yes! Bullet points make it clearer. There is a typo on line 1 though: "databased" instead of "databases".

**Comment by mauricioaniche** [comment]
Fixed!
