### ISSUE TITLE
@BeforeEach -> field initialisation

### ISSUE THREAD

**Issue by mauricioaniche** [sttp-book/sttp-book#186]
Make use of field initialisation instead of @BeforeEach, as the final effect is the same, and it reduces noise.

Note that this has an impact in the `code-examples` projects too. We need a combined PR here.

**Comment by mauricioaniche** [comment]
Note that, in the _test automation_ chapter, we explicitly discuss this refactor in the _refactoring_ subsection. So, please, no need to do it in this chapter.

**Comment by sf105** [comment]
Would it be better to start that way, and then discuss the refactoring in the context of "legacy" tests?

**Comment by mauricioaniche** [comment]
That's definitely an option! Maybe discussing test code in legacy systems could fit the _test engineering_ chapter.

Nevertheless, in other chapters, I think we can replace most of before's and use field initialisations directly.

**Comment by sf105** [comment]
Just to be clear, I was thinking of pre-existing tests as part of that legacy. So many people have learned JUnit on the fly that they miss details like this.

**Comment by mauricioaniche** [comment]
It seems most of our code was already using field initialisations, with the exception of the first snippets in _getting started_, which we refactor in a later section.
