### ISSUE TITLE
Chapter: web testing

### ISSUE THREAD

**Issue by mauricioaniche** [sttp-book/sttp-book#20]
A chapter on web testing. Cover:

- [x] Client-side
- [ ] Back end
- [x] Usability

What else?

**Comment by fm2003** [comment]
Here are some ideas from last year:

* Unit testing front-end 'logic' (e.g. date formatting utility functions):
  * JavaScript unit tests (Jasmine / JEST / Mocha + Chai).
  * Mocking (Jest).
  * Design for testability: clear separation between 'logic' and UI.
* Unit testing front-end components (e.g. Paged table):
  * Use React as an example
  * Design components with a clear programming interface: 'props' (React) as input, and rendered component as output. Make small, easily testable components.
  * Test various combinations of input and check whether the expected elements are in the output.
  * Test events: simulate a 'click' event and check the result.
  * Snapshot testing
* User interface (UI) testing:
  * Instrumenting the browser using Selenium
  * Cypress.io
  * Jest + Puppeteer?
  * Testing in a headless browser (PhantomJS, Puppeteer) vs a JavaScript DOM (JSDOM in JEST)
  * Cross-browser testing (not possible in Cypress for now, but possible in Selenium)
  * Challenges:
    * Resilience/consistency: account for differences in browser speed, page rendering etc. ("Click a button, wait for another element to appear, then check the result.") Make sure the tests give the same result every time. (This is solved in Cypress.io)
    * Test data: arriving at the right state so you can run the test. Add/use services so you can make arrive at that state right away.
    * Test data: by running the tests you will change the application state, so the initial state will be different when you run the tests again. Possible solution: rebuild the environment every time, or run a script that does a clean-up of selected things (in the database).
    * Finding elements on a page: for instance, include CSS classes so you can find elements.
    * Accounting for changes in the application: make sure the whole thing doesn't break when you add one element on a page. Maintainability.
* How to choose what to test, and how
  * Overlap between component tests and UI tests
  * Contrasting opinions with Maurício
* Automated accessibility testing
  * Might not have to dive to deep into this if we manage to get a guest lecture by the Wordpress lady.
	* aXe-core
	* Tenon API (commercial)
* Security testing (covered by Azqa)
* Responsive design testing
* Load testing
* The place for manual testing
  * Is it still required? Do we test everything automatically or still have some manual controls?
  * Much of accessibility requires manual testing.
  * Testing the logical flow of the application. Subjective user interface/interaction in general.
* Responsibility shift from testers to developers (nowadays developers write the tests, or testers gain development skills). End-to-end tests.
* Testing and Continuous integration: e.g. integration with Travis on Github. Challenges with end-to-end tests. BrowserStack. SauceLabs. Comparing to testing the user interface of JPacman (it needs X running).


Also, the schedule of the lecture was as follows (we can probably use a similar structure in the chapter):
* Overview with diagram (frontend, backend, db). Explaining what web testing is about, and what we are not going to talk about. Functionality testing (unit testing, end-to-end testing), security testing (penetration testing), performance testing (load testing), usability testing, cross-browser testing, accessibility testing
* Show the demo app
* Tell something about React
* JavaScript unit testing
  * relate to what they know
  * business logic
  * components
* UI component testing (input: props; output: HTML markup)
  * simple test
  * test with 2 branches
  * snapshot testing
  * testing events?
* End-to-end testing with Selenium
  * the story of QDelft (?)
  * what is end-to-end testing?
* Accessibility
  * Point them to a paper

**Comment by mauricioaniche** [comment]
Thanks for the very descriptive issue. You have covered different topics, indeed.

The schedule looks like a good story line:
- Short introduction of what web testing is and what is the difference from that they have seen so far. In here, you could choose the three big things we are going to test
- Thing 1: Unit testing front-end logic
- Thing 2: Testing a front-end component
- Thing 3: Back-end testing with Selenium (or Cypress), best practices and challenges in back-end testing
- Final discussion: Manual testing in web apps: still needed?

Topics such as accessibility, load testing, and security seem to deserve an entire chapter. I wouldn't give them so much priority right now, but focus more on having in-depth discussions and examples of the things above.

WDYT?
