### ISSUE TITLE
Comparison with number of atoms in universe is flawed

### ISSUE THREAD

**Issue by SimayyFox** [sttp-book/sttp-book#205]
https://sttp.site/chapters/getting-started/testing-principles.html states:
`This implies that we need to test all the possible combinations. A simple calculation shows us that 2 possible values for each of the 128 different flags gives 21282^{128}2​128​​ combinations that need to be tested. As a matter of comparison, this number is higher than the estimated number of atoms in the universe. In other words, this software system has more possible combinations to be tested than the universe has atoms.`

2^128 is 3.4*10^38, whilst according to sources at a Google search the number of atoms in the universe is in the order of 10^80. This means that the number of possible combinations is not higher than the number of atoms in the universe.

**Comment by mauricioaniche** [comment]
Great observation!

Maybe we should change 128 to a higher number, then! As the comparison with the number of atoms in the universe is quite a powerful one!

**Comment by SimayyFox** [comment]
I definitely agree! 256 would lead to an equal amount of atoms and combinations. Around 300 combinations would probably work best if we want to keep a greater number of combinations than  atoms (:

**Comment by mauricioaniche** [comment]
Do you want to open the PR yourself (and get the credits + bonus points)? :)

**Comment by SimayyFox** [comment]
Sure! I'll try it right now, thanks!

**Comment by mauricioaniche** [comment]
#207 fixes this!!
