### ISSUE TITLE
Outdated link to Code Injection Vulnaribility Discovery in the Security testing channel

### ISSUE THREAD

**Issue by MatthijsdeGoede** [sttp-book/sttp-book#226]
The following link: https://ivan.barreraoro.com.ar/signal-desktop-html-tag-injection/
Under the hyperlink with text: "Code Injection Vulnerability was discovered in the Desktop Signal app"
in the Security testing chapter cannot be reached anymore.

**Comment by fm2003** [comment]
For now, I have updated the link to an archived version on archive.org.

@azqa Can you find a better page that also talks about this vulnerability? Or are you fine with the archive.org link?

**Comment by azqa** [comment]
@fm2003 Oh, seems their account got suspended. Hackernews has a good write-up of the same vulnerability: https://thehackernews.com/2018/05/signal-desktop-hacking.html
