### ISSUE TITLE
There is no setup or @BeforeEach annotation in the code

### ISSUE THREAD

**Issue by djosh34** [sttp-book/sttp-book#236]
On this [line](https://github.com/sttp-book/sttp-book/blame/master/chapters/testing-techniques/specification-based-testing.md#L151) `BeforeEach` is mentioned, however in the code block prior there is no `setup` method nor `BeforeEach` annotation.

**Comment by mauricioaniche** [comment]
Thanks, @sf105 for the patch! And thanks @djosh34 for raising the issue!
