### ISSUE TITLE
Should improve clarity on (basic vs full) condition coverage

### ISSUE THREAD

**Issue by djosh34** [sttp-book/sttp-book#243]
Here in [exercise 9](https://github.com/sttp-book/sttp-book/blame/master/chapters/testing-techniques/structural-testing.md#L916) the exercise mentions condition coverage. However, there is ambiguity on which type of condition coverage is used. As basic and full condition coverage mean quite different things. According to the answers it should be full condition coverage. 

Is it expected from students that condition coverage = full condition coverage. If that's the case then it should be noted inside the condition coverage chapter, as that chapter only discusses basic condition coverage and not full condition coverage, while the video only discusses full condition coverage and ignores basic condition coverage. 

After a lot of google searching, I've come to the conclusion that there is a lot of ambiguity on the topic what exactly full condition coverage is. While basic condition coverage is quite clear, there doesn't seem to be a definitive name for full condition coverage.

**Comment by mauricioaniche** [comment]
Hi, @djosh34! 

Indeed, there's a bit of confusion in terminology! I just clarified that in the text.

(In the midterm, I made sure to mention branch+condition coverage. I'll double check whether this is also clear in the final endterm)

Thanks for noticing!
