### ISSUE TITLE
Add chapter numbers

### ISSUE THREAD

**Issue by Jasper-Nelligan** [sttp-book/sttp-book#273]
What do people think about adding chapter and section numbers? For example, section 1.1 would be the section "Why software testing?". My class just got assigned readings referred to as section 1.1 and 1.5, but there is no actual chapter numbers to match this. Adding chapter numbers could make finding the right reading easier.

**Comment by mauricioaniche** [comment]
Hi, Jasper!

I am, as we speak, moving all the content to a Latex document. The template I'm using add numbers to chapters, indeed. But this should only be done by March.

So, if you want to submit a PR that introduces chapter numbers while the latex version is not ready, feel free to do so!

**Comment by Jasper-Nelligan** [comment]
Alright, just submitted a PR. Let me know if I need to make any changes before merging. Thanks!
