### ISSUE TITLE
Chapter: 2.5 Design by Contracts - Use of assertions for argument checking in public methods

### ISSUE THREAD

**Issue by mroger** [sttp-book/sttp-book#290]
About this chapter, isn't advisable not to use assertions to check validity of public methods input parameters?

Excellent book, by the way! Thank you very much!

**Comment by mauricioaniche** [comment]
That's totally correct, @mroger! We simplified our explanation too much there, and kept the assertions throughout the chapter. The new version of the chapter does not make use of assertions!
