### ISSUE TITLE
Fix small issues in the PDF

### ISSUE THREAD

**Issue by mauricioaniche** [sttp-book/sttp-book#4]
The PDF has the following issues:

- [x] Images are broken (the conversion from SVG doesn't work)
- [x] Tables are broken (see the model-based chapter)
- [x] Images are too big / too small in some cases
- [x] Some text goes over margin. Maybe force latex to put them all inside the page limits?

**Comment by wouterpolet** [comment]
Can be closed when #68 and #69 are merged.
