### ISSUE TITLE
Reuse text on Page Objects and BDD

### ISSUE THREAD

**Issue by mauricioaniche** [sttp-book/sttp-book#42]
We had some text about Page Objects and BDD in the state machine chapter. Now that we will have a dedicated chapter on web testing, I suggest we see if that content fits that chapter.

I uploaded the old content here: [old-web-testing-content.txt](https://github.com/sttp-book/sttp-book/files/4399009/old-web-testing-content.txt)

PS: A reference I forgot to paste to the txt file:
```
* van Deursen, A. (2015). Beyond Page Objects: Testing Web Applications with State Objects. ACM Queue, 13(6), 20.
```

**Comment by fm2003** [comment]
Web testing chapter has been updated with these contents. Can you take a look and see whether that solves this issue?
