### ISSUE TITLE
Fix issues with the RomanNumeral requirement descriptions

### ISSUE THREAD

**Issue by fm2003** [sttp-book/sttp-book#44]
* The RomanNumeral example occurs in both `test-automation.md` and `tdd.md`. The descriptions in these two files differ. They should probably be identical.

* The one in `test-automation.md` first tells us that "The letters should be ordered from the highest to the lowest value.", but then goes on to say "Some numbers need to make use of a subtractive notation to be represented. Example: 9 is `IX`, 40 is `XL`, 14 is `XIV`." So then the letters are not ordered any more... This seems contradictory.

* While we're at it, it's probably a good idea not to include the example in backticks in `tdd.md`, because that messes up the Markdown formatting.

**Comment by HellboundHound** [comment]
As a student currently participating in SQT, can I be assigned to this issue please?

**Comment by mauricioaniche** [comment]
Great, @HellboundHound! Thanks for PR #97 !
