### ISSUE TITLE
Provide more clarity on the number of tests

### ISSUE THREAD

**Issue by fm2003** [sttp-book/sttp-book#45]
In `structural-testing.md`, there is the following sentence: 

> And interestingly, if our conditions have only a binary outcome, which is our case here, as conditions
either return true or false, the number of tests we will need for that is always "only" $$N+1$$, where $$N$$ is the number of conditions in the program. 
$$N+1$$ is definitely smaller than $$2^N$$!

(Previously, this sentence said $$N^2$$; this has been fixed already.)

From just reading this chapter alone, it is not very clear what the $$2^N$$ refers to. It may be helpful to refer back to boundary testing, and maybe also to specify the number of tests that you need to write in the other cases discussed in the structural testing chapter (like path coverage).

Also, in `boundary-testing.md` the number of test cases is never made explicit (with a formula) either. One example is given ($$4^5$$), but it would be nice to also put $$4^N$$ or $$m^N$$ somewhere (where by `m` I mean the number of test cases you decide to write for each of the conditions).

**Comment by mauricioaniche** [comment]
Explaining the 2^n: https://github.com/sttp-book/sttp-book/commit/3304510c323836710ce46e3dfdb60fe9db648beb

The other example was already removed from the boundary testing chapter.
