### ISSUE TITLE
Test automation: comments about the refactored test code

### ISSUE THREAD

**Issue by fm2003** [sttp-book/sttp-book#46]
The chapter `test-automation.md` now suggests that moving the construction of the `RomanNumeral` object to a method with a `@BeforeEach` annotation is an improvement (and condemns the reader if he thinks otherwise). I think a few things need to change here:

* Change the tone from "this is way better" to "if you want to do so, you have `@BeforeEach` at your disposal".
* Add some nuance, for instance by including a "hint" on what would happen when the constructor of `RomanNumeral` changes (and different tests may then need to use different constructors, so you'd have to move the line with `new` back into the test methods). And maybe some general comments about coupling between tests, and tests as being self-contained (or refer to a chapter that talks about this).

**Comment by mauricioaniche** [comment]
I don't think the current version of the text says "this is way better". Nevertheless, small improvement: https://github.com/sttp-book/sttp-book/commit/d55a9dc4434c4d41902fcf8f12a5fcf9f438ee8f

I also added a hint mentioning the case of multiple constructors, and that we discuss it later: https://github.com/sttp-book/sttp-book/commit/0723cd6f3d9e076b938bc689703e82045fea8be8
