### ISSUE TITLE
Concrete example for the MC/DC part

### ISSUE THREAD

**Issue by mauricioaniche** [sttp-book/sttp-book#51]
In the MC/DC, we test this generic `(A && ( B || C))` condition. Maybe giving it a story as well as some code would make it easier for students to understand.

PS: This suggestion came from a 2019 student.

**Comment by HellboundHound** [comment]
Hi Maurício,

I have made a PR (https://github.com/sttp-book/sttp-book/pull/122) regarding this issue.
I've added a code example with some more background. Apart from that I thought the MC/DC test deriving method to be hard to grasp. Therefore, I have tried slightly restructuring and adding more clarification. I would be keen to hear your feedback on my PR!

Kind regards,
Danny Breunissen

**Comment by HellboundHound** [comment]
Issue can be closed as PR https://github.com/sttp-book/sttp-book/pull/122 has been merged
