### ISSUE TITLE
Integrate new versions of RomanNumeral code into test-automation chapter

### ISSUE THREAD

**Issue by fm2003** [sttp-book/sttp-book#54]
There are new implementations of the RomanNumeral code at https://github.com/sttp-book/code-examples/tree/master/src/main/java/tudelft/roman. These need to be integrated into the `test-automation.md` chapter.

**Comment by mauricioaniche** [comment]
Done: https://github.com/sttp-book/sttp-book/commit/033fdb705921fb4ca27ed7b0135517167e26d574
