### ISSUE TITLE
Rename SUMMARY.md to TOC.md

### ISSUE THREAD

**Issue by fm2003** [sttp-book/sttp-book#55]
The file `SUMMARY.md` does not contain a summary, but rather a table of contents (a TOC). I propose to rename the file to `TOC.md`. If we do this, we should also update the scripts that create the website and the PDF.

**Comment by mauricioaniche** [comment]
Is this gitbook compliant? From what I know, gitbook expects the summary to be in the summary.md.

**Comment by mauricioaniche** [comment]
(Easy way to test: rename, and then `gitbook serve`)

**Comment by fm2003** [comment]
> 
> 
> Is this gitbook compliant? From what I know, gitbook expects the summary to be in the summary.md.

Ah, I did not know that. From their documentation:

> **summary:** Your documentation's table of content. Its default value is `./SUMMARY.md`

So it's an issue with GitBook, and not with our book specifically. I am closing this.
