### ISSUE TITLE
Structural testing: Is the section "More examples of Control-Flow Graphs" at the right place?

### ISSUE THREAD

**Issue by j0rd1smit** [sttp-book/sttp-book#92]
The subsection "More examples of Control-Flow Graphs" feels out of place at the very end. 
I think it will be better if we place it between "Blocks and Control-Flow Graph" & "Block coverage" because the last line of "Blocks and Control-Flow Graph" says: "Even when you use a different programming language to write the same program, you might end up with the same CFG.". If we do this change it might be better to change to section title "More examples of Control-Flow Graphs" to "Examples of Control-Flow Graphs in another language".

**Comment by mauricioaniche** [comment]
Did we solve this in the PR, @j0rd1smit? Shall we close this issue?

**Comment by j0rd1smit** [comment]
@mauricioaniche I wasn't sure if this was something you wanted. Anyway, I created a PR. You can use this PR to determine if this suggestion helps for the story flow or not.
