### ISSUE TITLE
Structural Testing: inconsistent notation for 100%

### ISSUE THREAD

**Issue by j0rd1smit** [sttp-book/sttp-book#93]
The notation used for 100% in text lines varies between inline math notation to normal notation. I think we should make it consistent. What do you think?

**Comment by mauricioaniche** [comment]
Great catch! I agree. Was this fully fixed in PR #94?

**Comment by j0rd1smit** [comment]
No not yet. I wasn't sure if this was intended and which option is preferred. So shall i change everything to math notation?

**Comment by mauricioaniche** [comment]
Oh, I missed your answer here, sorry, @j0rd1smit! I think we should take into consideration how it looks like in the book. Using the math notation kinda highlights the 100% in the text, so I'd say, let's use it if we want to draw attention to it!

**Comment by j0rd1smit** [comment]
Ah ok, yeah it indeed draws attention to the 100%. This attention will be lost if they all have the same style. Thus I no longer think it is an issue; it's a design choice. I will close the issue for now.
